import PDFDocument from 'pdfkit';

/**
 * Generate PDF report from analysis results
 * @param {Object} result - Analysis result
 * @returns {Promise<Buffer>} PDF buffer
 */
export async function generatePDFReport(result) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const chunks = [];
      
      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);
      
      // Header
      doc.fontSize(20).text('ATS Resume Analysis Report', { align: 'center' });
      doc.moveDown();
      doc.fontSize(12).text(`Resume: ${result.resumeName}`, { align: 'center' });
      doc.moveDown(2);
      
      // Overall Score
      doc.fontSize(16).text('Overall Match Score', { underline: true });
      doc.fontSize(24).fillColor('#0066cc').text(`${result.matchPercentage}%`, { align: 'center' });
      doc.fillColor('black').moveDown();
      
      // Score Breakdown
      doc.fontSize(14).text('Score Breakdown', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(11);
      doc.text(`Semantic Similarity: ${result.semanticSimilarity}%`);
      doc.text(`Keyword Match: ${result.keywordMatchScore}%`);
      doc.text(`Skill Relevance: ${result.skillRelevance}%`);
      doc.text(`Experience Match: ${result.experienceMatch}%`);
      doc.text(`Education Match: ${result.educationMatch}%`);
      doc.moveDown();
      
      // Formatting Analysis
      if (result.formattingAnalysis) {
        doc.fontSize(14).text('Formatting Analysis', { underline: true });
        doc.moveDown(0.5);
        doc.fontSize(11);
        doc.text(`ATS Readability Score: ${result.formattingAnalysis.atsReadabilityScore}%`);
        if (result.formattingAnalysis.issues.length > 0) {
          doc.moveDown(0.5);
          doc.text('Issues:', { underline: true });
          result.formattingAnalysis.issues.forEach(issue => {
            doc.text(`• ${issue}`, { indent: 20 });
          });
        }
        if (result.formattingAnalysis.warnings.length > 0) {
          doc.moveDown(0.5);
          doc.text('Warnings:', { underline: true });
          result.formattingAnalysis.warnings.forEach(warning => {
            doc.text(`• ${warning}`, { indent: 20 });
          });
        }
        doc.moveDown();
      }
      
      // Recommendations
      if (result.recommendations && result.recommendations.overall.length > 0) {
        doc.fontSize(14).text('Top Recommendations', { underline: true });
        doc.moveDown(0.5);
        doc.fontSize(11);
        result.recommendations.overall.slice(0, 10).forEach((rec, index) => {
          doc.text(`${index + 1}. ${rec.title}`, { bold: true });
          doc.text(rec.message, { indent: 20 });
          doc.moveDown(0.3);
        });
        doc.moveDown();
      }
      
      // Keywords
      if (result.topKeywords && result.topKeywords.length > 0) {
        doc.fontSize(14).text('Top Keywords Found', { underline: true });
        doc.moveDown(0.5);
        doc.fontSize(11);
        doc.text(result.topKeywords.slice(0, 20).join(', '));
        doc.moveDown();
      }
      
      // Missing Keywords
      if (result.keywordOptimization && result.keywordOptimization.recommendations.length > 0) {
        const missingKeywords = result.keywordOptimization.recommendations
          .filter(r => r.priority === 'high')
          .slice(0, 10);
        
        if (missingKeywords.length > 0) {
          doc.fontSize(14).text('Missing Keywords', { underline: true });
          doc.moveDown(0.5);
          doc.fontSize(11);
          missingKeywords.forEach(rec => {
            doc.text(`• ${rec.keyword}`, { indent: 20 });
          });
          doc.moveDown();
        }
      }
      
      // Footer
      doc.fontSize(8)
         .fillColor('gray')
         .text('Generated by ATS Scanner', 50, doc.page.height - 50, { align: 'center' });
      
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}
